### PR TITLE
Hugo modules

### PR DESCRIPTION
**Pull request by zregvart**
First commit: [Use Hugo modules instead of git submodules](https://github.com/konflux-ci/konflux-ci.github.io/commit/c68b3a9fcf3f780822175973bd5c62764d8c9a29) makes it a bit easier as one doesn't need to tackle with git submodules as Hugo will download the theme and the version can be updated using `hugo mod get -u`.

See https://gohugo.io/hugo-modules/use-modules/#use-a-module-for-a-theme

Second commit: [Pull static files into the themes directory](https://github.com/konflux-ci/konflux-ci.github.io/commit/e508cac4bc9f1097174012cc8bd753e117e625a4) makes the custom CSS and images available as a theme and thus reusable for efforts like https://github.com/konflux-ci/architecture/pull/183/

### CODE REVIEW

**Comment by yftacherzog** [comment]
@zregvart can we update the readme with the procedure for fetching the modules? (I was not able to make it work)

**Comment by zregvart** [comment]
@yftacherzog added a bit to the readme in https://github.com/konflux-ci/konflux-ci.github.io/compare/e508cac4bc9f1097174012cc8bd753e117e625a4..b6fda5619cb6e3f26d751f9e2369600bac0d108f. Do yell if that doesn't work for you...

**Review by yftacherzog — DISMISSED** [review]
> @yftacherzog added a bit to the readme in https://github.com/konflux-ci/konflux-ci.github.io/compare/e508cac4bc9f1097174012cc8bd753e117e625a4..b6fda5619cb6e3f26d751f9e2369600bac0d108f. Do yell if that doesn't work for you...

Thanks. Not sure what went wrong yesterday. It's working now.
lgtm.

**Comment by yftacherzog** [comment]
> > @yftacherzog added a bit to the readme in https://github.com/konflux-ci/konflux-ci.github.io/compare/e508cac4bc9f1097174012cc8bd753e117e625a4..b6fda5619cb6e3f26d751f9e2369600bac0d108f. Do yell if that doesn't work for you...
> 
> Thanks. Not sure what went wrong yesterday. It's working now. lgtm.

I now remember how I tested yesterday and it still doesn't work.
I cloned your fork on a new directory and fetched the PR branch. I then tried starting Hugo and I get `Error: command error: failed to load modules: failed to apply mounts for project: failed to open dir "/var/lib/snapd/void/website": "open /var/lib/snapd/void/website: no such file or directory"
`

This is what I did:

```bash
→ git clone git@github.com:zregvart/konflux-ci.github.io.git
Cloning into 'konflux-ci.github.io'...
remote: Enumerating objects: 262, done.
remote: Counting objects: 100% (88/88), done.
remote: Compressing objects: 100% (58/58), done.
remote: Total 262 (delta 33), reused 40 (delta 28), pack-reused 174
Receiving objects: 100% (262/262), 971.79 KiB | 2.72 MiB/s, done.
Resolving deltas: 100% (80/80), done.
(13:30:04) ○ [yherzog@yherzog-thinkpadp1gen5.tlv.csb] /tmp/tmp.Btxgu0XbJd 
→ cd konflux-ci.github.io/
/tmp/tmp.Btxgu0XbJd/konflux-ci.github.io
(13:30:05) ± [yherzog@yherzog-thinkpadp1gen5.tlv.csb] .../tmp.Btxgu0XbJd/konflux-ci.github.io (main ✓) 
→ git fetch 
(13:30:34) ± [yherzog@yherzog-thinkpadp1gen5.tlv.csb] .../tmp.Btxgu0XbJd/konflux-ci.github.io (main ✓) 
→ git checkout pr/hugo-modules-theme-module 
branch 'pr/hugo-modules-theme-module' set up to track 'origin/pr/hugo-modules-theme-module'.
Switched to a new branch 'pr/hugo-modules-theme-module'
(13:30:39) ± [yherzog@yherzog-thinkpadp1gen5.tlv.csb] .../tmp.Btxgu0XbJd/konflux-ci.github.io (pr/hugo-modules-theme-module ✓) 
→ hugo --source website server -D
Hugo provides its own webserver which builds and serves the site.
While hugo server is high performance, it is a webserver with limited options.

The `hugo server` command will by default write and serve files from disk, but
you can render to memory by using the `--renderToMemory` flag. This can be
faster in some cases, but it will consume more memory.

By default hugo will also watch your files for any changes you make and
automatically rebuild the site. It will then live reload any open browser pages
and push the latest content to them. As most Hugo sites are built in a fraction
of a second, you will be able to save and see your changes nearly instantly.

Usage:
  hugo server [command] [flags]
  hugo server [command]

Aliases:
  server, serve

Available Commands:
  trust       Install the local CA in the system trust store.

Flags:
      --appendPort               append port to baseURL (default true)
  -b, --baseURL string           hostname (and path) to the root, e.g. https://spf13.com/
      --bind string              interface to which the server will bind (default "127.0.0.1")
  -D, --buildDrafts              include content marked as draft
  -E, --buildExpired             include expired content
  -F, --buildFuture              include content with publishdate in the future
      --cacheDir string          filesystem path to cache directory
      --cleanDestinationDir      remove files from destination not found in static directories
  -c, --contentDir string        filesystem path to content directory
      --disableBrowserError      do not show build errors in the browser
      --disableFastRender        enables full re-renders on changes
      --disableKinds strings     disable different kind of pages (home, RSS etc.)
      --disableLiveReload        watch without enabling live browser reload on rebuild
      --enableGitInfo            add Git revision, date, author, and CODEOWNERS info to the pages
      --forceSyncStatic          copy all files when static is changed.
      --gc                       enable to run some cleanup tasks (remove unused cache files) after the build
  -h, --help                     help for server
      --ignoreCache              ignores the cache directory
  -l, --layoutDir string         filesystem path to layout directory
      --liveReloadPort int       port for live reloading (i.e. 443 in HTTPS proxy situations) (default -1)
      --minify                   minify any supported output format (HTML, XML etc.)
      --navigateToChanged        navigate to changed content file on live browser reload
      --noBuildLock              don't create .hugo_build.lock file
      --noChmod                  don't sync permission mode of files
      --noHTTPCache              prevent HTTP caching
      --noTimes                  don't sync modification time of files
      --panicOnWarning           panic on first WARNING log
      --poll string              set this to a poll interval, e.g --poll 700ms, to use a poll based approach to watch for file system changes
  -p, --port int                 port on which the server will listen (default 1313)
      --pprof                    enable the pprof server (port 8080)
      --printI18nWarnings        print missing translations
      --printMemoryUsage         print memory usage to screen at intervals
      --printPathWarnings        print warnings on duplicate target paths etc.
      --printUnusedTemplates     print warnings on unused templates.
      --renderSegments strings   named segments to render (configured in the segments config)
      --renderStaticToDisk       serve static files from disk and dynamic files from memory
      --templateMetrics          display metrics about template executions
      --templateMetricsHints     calculate some improvement hints when combined with --templateMetrics
  -t, --theme strings            themes to use (located in /themes/THEMENAME/)
      --tlsAuto                  generate and use locally-trusted certificates.
      --tlsCertFile string       path to TLS certificate file
      --tlsKeyFile string        path to TLS key file
      --trace file               write trace to file (not useful in general)
  -w, --watch                    watch filesystem for changes and recreate as needed (default true)

Global Flags:
      --clock string               set the clock used by Hugo, e.g. --clock 2021-11-06T22:30:00.00+09:00
      --config string              config file (default is hugo.yaml|json|toml)
      --configDir string           config dir (default "config")
      --debug                      debug output
  -d, --destination string         filesystem path to write files to
  -e, --environment string         build environment
      --ignoreVendorPaths string   ignores any _vendor for module paths matching the given Glob pattern
      --logLevel string            log level (debug|info|warn|error)
      --quiet                      build in quiet mode
      --renderToMemory             render to memory (mostly useful when running the server)
  -s, --source string              filesystem path to read files relative from
      --themesDir string           filesystem path to themes directory
  -v, --verbose                    verbose output

Use "hugo server [command] --help" for more information about a command.

Error: command error: failed to load modules: failed to apply mounts for project: failed to open dir "/var/lib/snapd/void/website": "open /var/lib/snapd/void/website: no such file or directory"

```

**Comment by yftacherzog** [comment]
> > > @yftacherzog added a bit to the readme in https://github.com/konflux-ci/konflux-ci.github.io/compare/e508cac4bc9f1097174012cc8bd753e117e625a4..b6fda5619cb6e3f26d751f9e2369600bac0d108f. Do yell if that doesn't work for you...
> > 
> > 
> > Thanks. Not sure what went wrong yesterday. It's working now. lgtm.
> 
> I now remember how I tested yesterday and it still doesn't work. I cloned your fork on a new directory and fetched the PR branch. I then tried starting Hugo and I get `Error: command error: failed to load modules: failed to apply mounts for project: failed to open dir "/var/lib/snapd/void/website": "open /var/lib/snapd/void/website: no such file or directory" `

It might be unrelated to your PR though. Hang on.

**Review by yftacherzog — APPROVED** [review]
Sorry for the mess. I attributed the failure for the change, but it was in fact caused by some unrelated limitation (I wanted a fresh clone of the repo so cloned it in temp and snap does not allow Hugo to run from there or something like this).

I tested again and it's working.

Thanks again!

**Comment by zregvart** [comment]
Glad it works on more than one machine :) I'm going to merge now...

**Comment by zregvart** [comment]
The [website](https://konflux-ci.dev/) looks the okay as well...

**Pull request merged**
